In [ ]:
# STRINGS
text = "Toto je text"
text2 = 'Toto je text2'

#text3 = "Toto je \"veta\"" # \n \t \'
#print(text3)
text4 = "Toto je \"veta\" a teraz \nnovy riadok"
print(text4)

text5 = """ Riadok1
Riadok2
Riadok3
"""
print(text5)
text = "TEXT2"
print(text[0])
print(text[2])
print(text[-1])
print(text[-2])
print(text[1:4])
print(text[:3])
print(text[2:])
string1 = "slovo1"
string2 = "slovo2"

string3 = string1 + " " + string2
print(string3)
print(3 * "Novak ")
bratislava = "Bratislava je pekna."
print(bratislava.split("a"))
print(bratislava.split(" "))
bratislava = "Bratislava je pekna."
print(bratislava.upper())
print(bratislava.lower())
print(bratislava.title())
print(bratislava.replace("a", "$"))
print(len(bratislava))

slovo1 = "abcd"
slovo2 = slovo1
print("kopia:" + slovo2) #kopia

# Tuples ()  nemenne
coords = (10, 20, 15)
print(coords)
clovek = ("Otto", 20, 30, True, coords)
print(clovek)
print(coords[0])
print(clovek[1:3])

# Lists [] menne
a = ["a", "b", "c"]
print(a)
a.append(5)
print(a)
a.remove("b")
print(a)
a = ["a", "b", "c"]
a.insert(2,"slovo")
print(a)
del a[-1]
print(a)

cisla = [2, 5, 7, 1, 10]
cisla.sort()
print(cisla)
cisla2 = [2, 5, 3, 1, 10]
print(sorted(cisla2))
cisla2 = [4, 5, 3, 1, 10]
cisla2.reverse()
print(cisla2)
cisla2 = [4, 5, 3, 1, 10]
print(cisla2[2:])